version: '3.8'
services:
  backend:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./.env
    links:
      - redis
    build:
      context: ./
    ports:
      - 8081:8080
