version: '3.8'
services:
  backend:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./.env-dev
    links:
      - redis
    build:
      context: ./
    ports:
      - 8080:8080
