version: '3.8'
services:
  backend:
    environment:
      - DATABASE_URL=mysql://root:j4onYumQmrJ263tkbdqZwEEw6@host.docker.internal:3306/board-dev
      - UID=u-s4t2ud-f3ca5ef0da2e919c39b4c97ed05d38332780ab544eff6503849f4a83a9fcc4f7
      - SECRET=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
    links:
      - redis
    build:
      context: ./
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: always
    logging:
      driver: none
